apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-APP
  namespace: gitops
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc 
  project: app-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/app-of-apps
    repoURL: https://github.com/Ujstor/k3s-prod-iac
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
