apiVersion: v1
kind: Secret
metadata:
  name: k3s1-cluster-secret
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: k3s1-cluster
  server: https://api.k3s1.ujstor.com
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: k3s1-cluster
      cluster:
        certificate-authority-data: <your-ca-data>
        server: https://api.k3s1.ujstor.com
    contexts:
    - name: k3s1-cluster
      context:
        cluster: k3s1-cluster
        user: k3s1-admin
    current-context: k3s1-cluster
    users:
    - name: k3s1-admin
      user:
        client-certificate-data: <your-cert-data>
        client-key-data: <your-key-data>
