portfolio:
  ingress:
    annotations: 
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: astipan.com
        paths:
          - path: /
            pathType: Prefix
    tls:
     - secretName: portfolio-prod-tls
       hosts:
         - astipan.com

