plausible:
  plausible-analytics:
    baseURL: https://analytics.ujstor.com

  customIngress:
    enabled: true
    hosts:
      - host: analytics.ujstor.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: plausible-analytics-prod-tls
        hosts:
          - analytics.ujstor.com
