gitea-k3s:
  gitea:
    ingress:
      enabled: true
      hosts:
        - host: gitea.k3s0.ujstor.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - gitea.k3s0.ujstor.com

    config:
      service:
        DISABLE_REGISTRATION: true
        REQUIRE_SIGNIN_VIEW: true

    persistence:
      size: 80Gi
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    redis:
      enabled: true
    postgresql:
      enabled: true
      primary:
        persistence:
          size: 5Gi
