notes-flask:
  ingress:
    annotations: 
      cert-manager.io/cluster-issuer: "letsencrypt" 
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: notes-flask.astipan.com
        paths:
          - path: /
            pathType: Prefix
    tls:
     - secretName: notes-flask-prod-tls
       hosts:
         - notes-flask.astipan.com
