apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cluster-aoa
  namespace: gitops
spec:
  destination:
    namespace: gitops
    server: https://api.k3s1.ujstor.com
  project: default
  source:
    path: cluster/k3s1-app/helm/app-of-apps
    repoURL: https://github.com/Ujstor/k3s-prod-iac
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
