apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cilium
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/system/cilium
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: cilium
  syncPolicy:
    automated:
      selfHeal: true
