apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-metallb-config
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-dependency: system-metallb-operator
spec:
  destination:
    namespace: metallb
    server: https://api.k3s1.ujstor.com:6443
  project: app-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/system/metallb-config
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: metallb-config
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
