apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cluster-issuer
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-dependency: system-cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://api.k3s1.ujstor.com
  project: app-cluster-bootstrap
  source:
    path: cluster/k3s0-ops/helm/cluster-issuer
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: cluster-issuer
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
