apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-postgres-operator
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    namespace: postgres-operator
    server: https://api.k3s1.ujstor.com:6443
  project: app-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/system/postgres-operator
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: postgres-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
