apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-external-secrets-app-cluster
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  destination:
    namespace: external-secrets
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/system/external-secrets
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
