apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-todo-go-htmx-k3s1
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    "argocd.argoproj.io/hook": "PreSync"
    "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"
spec:
  destination:
    namespace: todo-go-htmx
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/apps/todo-go-htmx
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: todo-go-htmx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
