apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-notes-flask
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  destination:
    namespace: notes-flask
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/apps/notes-flask
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: notes-flask
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
