apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-todo-django-k3s1
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  destination:
    namespace: django-todo
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/apps/todo-django
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: django-todo
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
