apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uptime-kuma
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  destination:
    namespace: uptime-kuma
    server: https://api.k3s1.ujstor.com:6443
  project: app-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/apps/uptime-kuma
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: uptime-kuma
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
