apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cilium-k3s0
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s0-ops/helm/system/cilium
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: cilium
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
