apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gitlab-k3s0
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s0-ops/helm/apps/gitlab
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: gitlab
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
